package tkom.utils;

public enum NodeType {
    PROGRAM,
    FUNCTION,
    STATEMENT_BLOCK,
    WHILE_STATEMENT,
    RETURN_STATEMENT,
    EXPRESSION,
    INIT_STATEMENT,
    ASSIGN_STATEMENT,
    FUNCTION_CALL,
    VARIABLE,
    CONDITION,
    INT,
    CURRENCY,
    IF_STATEMENT
}
